In [34]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report,confusion_matrix,recall_score,accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

%matplotlib inline

In [35]:
data  = pd.read_csv('D:/14_My Practice/Datasets/Social_Network_Ads.csv')
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [37]:
X = data.drop(['User ID','Gender','Purchased'],axis=1)
y = data.Purchased

In [38]:
X.shape

(400, 2)

In [39]:
y.shape

(400,)

In [40]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=30)

In [41]:
standscale = StandardScaler()
standscale.fit(X_train)
X_train_scaled =  standscale.transform(X_train)
X_test_scaled = standscale.transform(X_test)

In [42]:
X_train_scaled

array([[-0.7360978 ,  0.30125257],
       [-1.11392985,  0.30125257],
       [ 1.62535252,  1.6363853 ],
       [ 0.86968842,  1.10233221],
       [-0.83055581,  0.15290449],
       [-1.11392985, -1.03388016],
       [ 1.15306246, -1.00421055],
       [ 0.39739835,  0.30125257],
       [ 1.4364365 ,  1.01332336],
       [ 0.86968842, -0.67784477],
       [ 1.05860445,  0.56827911],
       [ 0.20848233,  0.06389564],
       [-0.92501383, -0.32180937],
       [ 0.68077239, -1.12288901],
       [ 1.53089451,  0.00455641],
       [-1.4917619 , -1.27123709],
       [-1.11392985, -0.79652323],
       [ 0.68077239, -1.41958517],
       [-1.77513594, -1.30090671],
       [ 2.00318458,  0.39026142],
       [-0.26380774, -1.47892441],
       [ 1.24752047,  1.90341184],
       [-0.64163979, -0.35147899],
       [-1.30284588, -1.27123709],
       [ 0.20848233,  0.15290449],
       [ 0.77523041,  0.5386095 ],
       [ 0.39739835,  1.01332336],
       [-1.30284588,  0.41993103],
       [ 1.05860445,

In [43]:
X_test_scaled

array([[-0.26380774, -1.27123709],
       [ 1.53089451,  1.01332336],
       [-0.26380774, -0.26247014],
       [-0.54718178, -1.53826364],
       [ 0.39739835,  0.09356525],
       [-0.26380774,  0.27158295],
       [ 0.77523041,  0.27158295],
       [ 0.68077239,  1.814403  ],
       [ 0.30294034,  0.30125257],
       [-0.64163979, -1.62727249],
       [-1.77513594, -1.50859402],
       [-1.11392985,  0.06389564],
       [-0.45272376, -0.02511321],
       [-0.26380774, -0.32180937],
       [-1.20838787,  0.30125257],
       [-1.01947184, -0.38114861],
       [-0.35826575, -0.79652323],
       [-1.11392985,  0.41993103],
       [ 2.09764259, -1.06354978],
       [-0.16934972,  0.86497528],
       [-0.26380774,  0.03422602],
       [-1.4917619 , -0.44048784],
       [-1.01947184, -1.47892441],
       [ 2.00318458,  0.1825741 ],
       [ 0.30294034, -0.5591663 ],
       [-0.92501383,  0.50893988],
       [ 0.96414643, -1.0932194 ],
       [ 0.86968842, -1.18222824],
       [-0.92501383,

In [44]:
X_test_scaled = pd.DataFrame(X_test_scaled,columns=X_test.columns)
X_train_scaled = pd.DataFrame(X_train_scaled,columns=X_train.columns)

In [45]:
X_test_scaled

Age  EstimatedSalary
0   -0.263808        -1.271237
1    1.530895         1.013323
2   -0.263808        -0.262470
3   -0.547182        -1.538264
4    0.397398         0.093565
..        ...              ...
115 -1.208388         0.508940
116  0.208482        -0.143792
117 -0.736098        -1.567933
118 -0.830556        -1.241567
119 -0.641640         0.034226

[120 rows x 2 columns]

In [46]:
X_train_scaled

Age  EstimatedSalary
0   -0.736098         0.301253
1   -1.113930         0.301253
2    1.625353         1.636385
3    0.869688         1.102332
4   -0.830556         0.152904
..        ...              ...
275  0.019566        -0.588836
276  1.058604        -0.915202
277 -1.775136         0.449601
278  0.964146         0.123235
279 -0.074892         0.212244

[280 rows x 2 columns]

In [47]:
standscale.mean_

array([3.77928571e+01, 6.98464286e+04])

In [48]:
X_test_scaled

Age  EstimatedSalary
0   -0.263808        -1.271237
1    1.530895         1.013323
2   -0.263808        -0.262470
3   -0.547182        -1.538264
4    0.397398         0.093565
..        ...              ...
115 -1.208388         0.508940
116  0.208482        -0.143792
117 -0.736098        -1.567933
118 -0.830556        -1.241567
119 -0.641640         0.034226

[120 rows x 2 columns]

In [49]:
X_train_scaled

Age  EstimatedSalary
0   -0.736098         0.301253
1   -1.113930         0.301253
2    1.625353         1.636385
3    0.869688         1.102332
4   -0.830556         0.152904
..        ...              ...
275  0.019566        -0.588836
276  1.058604        -0.915202
277 -1.775136         0.449601
278  0.964146         0.123235
279 -0.074892         0.212244

[280 rows x 2 columns]

In [50]:
nbc = GaussianNB()
nbc.fit(X_train_scaled,y_train)

GaussianNB()

In [51]:
y_pred = nbc.predict(X_test_scaled)
y_pred

array([0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [52]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.88      0.95      0.91        76
           1       0.89      0.77      0.83        44

    accuracy                           0.88       120
   macro avg       0.89      0.86      0.87       120
weighted avg       0.88      0.88      0.88       120



In [53]:
print(confusion_matrix(y_test,y_pred))

[[72  4]
 [10 34]]


In [54]:
print(recall_score(y_test,y_pred))

0.7727272727272727


In [55]:
print(accuracy_score(y_test,y_pred))

0.8833333333333333
