In [1]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report,confusion_matrix,recall_score,accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

%matplotlib inline

In [2]:
data  = pd.read_csv('D:/14_My Practice/Datasets/Social_Network_Ads.csv')
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
Gender = pd.get_dummies(data.Gender)
Gender

Female  Male
0         0     1
1         0     1
2         1     0
3         1     0
4         0     1
..      ...   ...
395       1     0
396       0     1
397       1     0
398       0     1
399       1     0

[400 rows x 2 columns]

In [4]:
data = pd.concat([Gender,data],axis=1)

In [5]:
X = data.drop(['User ID','Gender','Purchased'],axis=1)
y = data.Purchased

In [6]:
X.shape

(400, 4)

In [7]:
y.shape

(400,)

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=30)

In [9]:
standscale = StandardScaler()
standscale.fit(X_train)
X_train_scaled =  standscale.transform(X_train)
X_test_scaled = standscale.transform(X_test)

In [10]:
X_train_scaled

array([[-1.07417231,  1.07417231, -0.7360978 ,  0.30125257],
       [-1.07417231,  1.07417231, -1.11392985,  0.30125257],
       [ 0.93094934, -0.93094934,  1.62535252,  1.6363853 ],
       ...,
       [-1.07417231,  1.07417231, -1.77513594,  0.44960065],
       [-1.07417231,  1.07417231,  0.96414643,  0.12323487],
       [-1.07417231,  1.07417231, -0.07489171,  0.21224372]])

In [11]:
X_test_scaled

array([[-1.07417231,  1.07417231, -0.26380774, -1.27123709],
       [ 0.93094934, -0.93094934,  1.53089451,  1.01332336],
       [-1.07417231,  1.07417231, -0.26380774, -0.26247014],
       [-1.07417231,  1.07417231, -0.54718178, -1.53826364],
       [-1.07417231,  1.07417231,  0.39739835,  0.09356525],
       [-1.07417231,  1.07417231, -0.26380774,  0.27158295],
       [-1.07417231,  1.07417231,  0.77523041,  0.27158295],
       [ 0.93094934, -0.93094934,  0.68077239,  1.814403  ],
       [ 0.93094934, -0.93094934,  0.30294034,  0.30125257],
       [ 0.93094934, -0.93094934, -0.64163979, -1.62727249],
       [-1.07417231,  1.07417231, -1.77513594, -1.50859402],
       [ 0.93094934, -0.93094934, -1.11392985,  0.06389564],
       [ 0.93094934, -0.93094934, -0.45272376, -0.02511321],
       [-1.07417231,  1.07417231, -0.26380774, -0.32180937],
       [-1.07417231,  1.07417231, -1.20838787,  0.30125257],
       [ 0.93094934, -0.93094934, -1.01947184, -0.38114861],
       [-1.07417231,  1.

In [12]:
X_test_scaled = pd.DataFrame(X_test_scaled,columns=X_test.columns)
X_train_scaled = pd.DataFrame(X_train_scaled,columns=X_train.columns)

In [13]:
X_test_scaled

Female      Male       Age  EstimatedSalary
0   -1.074172  1.074172 -0.263808        -1.271237
1    0.930949 -0.930949  1.530895         1.013323
2   -1.074172  1.074172 -0.263808        -0.262470
3   -1.074172  1.074172 -0.547182        -1.538264
4   -1.074172  1.074172  0.397398         0.093565
..        ...       ...       ...              ...
115 -1.074172  1.074172 -1.208388         0.508940
116 -1.074172  1.074172  0.208482        -0.143792
117 -1.074172  1.074172 -0.736098        -1.567933
118  0.930949 -0.930949 -0.830556        -1.241567
119  0.930949 -0.930949 -0.641640         0.034226

[120 rows x 4 columns]

In [14]:
X_train_scaled

Female      Male       Age  EstimatedSalary
0   -1.074172  1.074172 -0.736098         0.301253
1   -1.074172  1.074172 -1.113930         0.301253
2    0.930949 -0.930949  1.625353         1.636385
3    0.930949 -0.930949  0.869688         1.102332
4   -1.074172  1.074172 -0.830556         0.152904
..        ...       ...       ...              ...
275  0.930949 -0.930949  0.019566        -0.588836
276  0.930949 -0.930949  1.058604        -0.915202
277 -1.074172  1.074172 -1.775136         0.449601
278 -1.074172  1.074172  0.964146         0.123235
279 -1.074172  1.074172 -0.074892         0.212244

[280 rows x 4 columns]

In [15]:
standscale.mean_

array([5.35714286e-01, 4.64285714e-01, 3.77928571e+01, 6.98464286e+04])

In [16]:
X_test_scaled

Female      Male       Age  EstimatedSalary
0   -1.074172  1.074172 -0.263808        -1.271237
1    0.930949 -0.930949  1.530895         1.013323
2   -1.074172  1.074172 -0.263808        -0.262470
3   -1.074172  1.074172 -0.547182        -1.538264
4   -1.074172  1.074172  0.397398         0.093565
..        ...       ...       ...              ...
115 -1.074172  1.074172 -1.208388         0.508940
116 -1.074172  1.074172  0.208482        -0.143792
117 -1.074172  1.074172 -0.736098        -1.567933
118  0.930949 -0.930949 -0.830556        -1.241567
119  0.930949 -0.930949 -0.641640         0.034226

[120 rows x 4 columns]

In [17]:
X_train_scaled

Female      Male       Age  EstimatedSalary
0   -1.074172  1.074172 -0.736098         0.301253
1   -1.074172  1.074172 -1.113930         0.301253
2    0.930949 -0.930949  1.625353         1.636385
3    0.930949 -0.930949  0.869688         1.102332
4   -1.074172  1.074172 -0.830556         0.152904
..        ...       ...       ...              ...
275  0.930949 -0.930949  0.019566        -0.588836
276  0.930949 -0.930949  1.058604        -0.915202
277 -1.074172  1.074172 -1.775136         0.449601
278 -1.074172  1.074172  0.964146         0.123235
279 -1.074172  1.074172 -0.074892         0.212244

[280 rows x 4 columns]

In [18]:
nbc = GaussianNB()
nbc.fit(X_train_scaled,y_train)

GaussianNB()

In [19]:
y_pred = nbc.predict(X_test_scaled)
y_pred

array([0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [20]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.86      0.95      0.90        76
           1       0.89      0.73      0.80        44

    accuracy                           0.87       120
   macro avg       0.87      0.84      0.85       120
weighted avg       0.87      0.87      0.86       120



In [21]:
print(confusion_matrix(y_test,y_pred))

[[72  4]
 [12 32]]


In [22]:
print(recall_score(y_test,y_pred))

0.7272727272727273


In [23]:
print(accuracy_score(y_test,y_pred))

0.8666666666666667
